version: '1.0'
services:
  mpc_dotnetc_user_server:
    container_name: ${DOCKER_CONTAINER_NAME}
    image: ${DOCKER_CONTAINER_IMAGE_NAME}
    network:
	- mpc_dotnetc_user_server_link_mpc_redis_user_session_cache_database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    ports:
      - ${SERVER_NETWORK_PORT_NUMBER}:${DOCKER_CONTAINER_PORT_NUMBER}
    env_file:
      - .env
volumes:
  data:
networks:
  mpc_dotnetc_user_server_link_mpc_redis_user_session_cache_database:
    external: true