version: '1.0'
services:
  mpc_dotnetc_user_server:
    container_name: ${DOCKER_CONTAINER_NAME}
    image: ${DOCKER_CONTAINER_IMAGE_NAME}
    build: ./Dockerfile
    volumes:
      - ./data:/data
    ports:
      - ${SERVER_NETWORK_PORT_NUMBER}:80
volumes:
  data:



