using mpc_dotnetc_user_server.Models.Report;
using mpc_dotnetc_user_server.Models.Users.Account_Groups;
using mpc_dotnetc_user_server.Models.Users.Account_Roles;
using mpc_dotnetc_user_server.Models.Users.Authentication.JWT;
using mpc_dotnetc_user_server.Models.Users.Authentication.Login.Email;
using mpc_dotnetc_user_server.Models.Users.Authentication.Login.TimeStamps;
using mpc_dotnetc_user_server.Models.Users.Authentication.Login.Twitch;
using mpc_dotnetc_user_server.Models.Users.Authentication.Logout;
using mpc_dotnetc_user_server.Models.Users.Authentication.Register.Email_Address;
using mpc_dotnetc_user_server.Models.Users.Feedback;
using mpc_dotnetc_user_server.Models.Users.Friends;
using mpc_dotnetc_user_server.Models.Users.Identity;
using mpc_dotnetc_user_server.Models.Users.Report;
using mpc_dotnetc_user_server.Models.Users.Selected.Alignment;
using mpc_dotnetc_user_server.Models.Users.Selected.Avatar;
using mpc_dotnetc_user_server.Models.Users.Selected.Deactivate;
using mpc_dotnetc_user_server.Models.Users.Selected.Language;
using mpc_dotnetc_user_server.Models.Users.Selected.Name;
using mpc_dotnetc_user_server.Models.Users.Selected.Navbar_Lock;
using mpc_dotnetc_user_server.Models.Users.Selected.Password_Change;
using mpc_dotnetc_user_server.Models.Users.Selected.Status;
using mpc_dotnetc_user_server.Models.Users.Selection;
using mpc_dotnetc_user_server.Models.Users.WebSocket_Chat;

namespace mpc_dotnetc_user_server.Interfaces
{
    public interface IUsers_Repository
    {
        Task<string> Create_Reported_Record(Reported dto);
        Task<bool> Create_Comment_Box_Record(Comment_Box dto);
        Task<bool> Create_Broken_Link_Record(Reported_Broken_Link dto);
        Task<bool> Create_Discord_Bot_Bug_Record(Reported_Discord_Bot_Bug dto);
        Task<string> Create_WebSocket_Log_Record(WebSocket_Chat_Permission dto);
        Task<bool> Create_Website_Bug_Record(Reported_Website_Bug dto);
        Task<bool> Create_End_User_Status_Record(Selected_Status dto);
        Task<string> Update_End_User_Account_Roles(Account_Role dto);
        Task<string> Update_End_User_Account_Groups(Account_Group dto);
        Task<bool> Create_Contact_Us_Record(Contact_Us dto);
        Task<string> Create_Pending_Email_Registration_Record(Pending_Email_Registration dto);
        Task<User_Data_DTO> Create_Account_By_Email(Complete_Email_Registration dto);
        Task<User_Data_DTO> Integrate_Account_By_Email(Complete_Email_Registration dto);
        Task Integrate_Account_By_Twitch(Complete_Twitch_Integration dto);
        Task<User_Data_DTO> Create_Account_By_Twitch(Complete_Twitch_Registeration dto);
        Task<string> Create_Reported_User_Profile_Record(Reported_Profile dto);
        Task<string> Delete_Account_By_User_id(Delete_User dto);
        Task<string> Insert_End_User_Login_Time_Stamp_History(Login_Time_Stamp_History dto);
        Task<string> Insert_Report_Email_Registration(Report_Email_Registration dto);
        Task<User_Data_DTO> Read_User_Data_By_ID(long end_user_id);
        Task<string> Read_User_Profile_By_ID(long end_user_id);
        Task<string> Read_WebSocket_Permission_Record_For_Both_End_Users(WebSocket_Chat_Permission dto);
        Task<string> Read_End_User_WebSocket_Sent_Chat_Requests(long end_user_id);
        Task<string> Read_End_User_WebSocket_Sent_Chat_Blocks(long end_user_id);
        Task<string> Read_End_User_WebSocket_Sent_Chat_Approvals(long end_user_id);
        Task<string> Read_End_User_WebSocket_Received_Chat_Requests(long end_user_id);
        Task<string> Read_End_User_WebSocket_Received_Chat_Blocks(long end_user_id);
        Task<string> Read_End_User_WebSocket_Received_Chat_Approvals(long end_user_id);
        Task<string> Read_End_User_Friend_Permissions_By_ID(long end_user_id);
        Task<byte> Read_End_User_Selected_Status(long user_id);
        Task<byte[]?> Read_User_Password_Hash_By_ID(long id);
        Task<long> Read_User_ID_By_Email_Address(string email_address);
        Task<string?> Read_User_Email_By_ID(long id);
        Task<string> Insert_Pending_Email_Registration_History_Record(Pending_Email_Registration_History dto);
        Task<string> Insert_Report_Failed_Email_Login_History_Record(Report_Failed_Email_Login_History dto);
        Task<string> Insert_Report_Failed_Logout_History(Report_Failed_Logout_History dto);
        Task<string> Insert_Report_Failed_Unregistered_Email_Login_History_Record(Report_Failed_Unregistered_Email_Login_History dto);
        Task<string> Insert_Report_Failed_Pending_Email_Registration_History(Report_Failed_Pending_Email_Registration_History dto);
        Task<string> Insert_Report_Failed_JWT_History_Record(Report_Failed_JWT_History dto);
        Task<string> Insert_Report_Failed_User_Agent_History(Report_Failed_User_Agent_History dto);
        Task<string> Update_Pending_Email_Registration_Record(Pending_Email_Registration dto);
        Task<string> Update_End_User_Avatar(Selected_Avatar dto);
        Task<string> Update_End_User_Avatar_Title(Selected_Avatar_Title dto);
        Task<string> Update_End_User_Name(Selected_Name dto);
        Task<string> Update_End_User_Login_Time_Stamp(Login_Time_Stamp dto);
        Task<string> Update_End_User_Logout(Logout_Time_Stamp dto);
        Task<string> Insert_End_User_Logout_History_Record(Logout_Time_Stamp dto);
        Task<string> Insert_Report_Failed_Selected_History(Report_Failed_Selected_History dto);
        Task<string> Update_End_User_Selected_Alignment(Selected_App_Alignment dto);
        Task<string> Update_End_User_Selected_Text_Alignment(Selected_App_Text_Alignment dto);
        Task<string> Update_End_User_Selected_Language(Selected_Language dto);
        Task<string> Update_End_User_Selected_Nav_Lock(Selected_Navbar_Lock dto);
        Task<string> Update_End_User_Selected_Status(Selected_Status dto);
        Task<string> Update_End_User_Selected_Theme(Selected_Theme dto);
        Task<string> Update_End_User_Selected_Grid_Type(Selected_App_Grid_Type dto);
        Task<string> Update_End_User_First_Name(Identities dto);
        Task<string> Update_End_User_Last_Name(Identities dto);
        Task<string> Update_End_User_Middle_Name(Identities dto);
        Task<string> Update_End_User_Maiden_Name(Identities dto);
        Task<string> Update_End_User_Ethnicity(Identities dto);
        Task<string> Update_End_User_Gender(Identities dto);
        Task<string> Update_End_User_Password(Password_Change dto);
        Task<string> Update_Chat_Web_Socket_Permissions(WebSocket_Chat_Permission dto);
        Task<string> Update_Friend_Permissions(Friends_Permission dto);
        Task<string> Delete_From_Web_Socket_Chat_Permissions(WebSocket_Chat_Permission dto);
        Task<string> Update_End_User_Birth_Date(Identities dto);
        Task<string> Update_End_User_Card_Border_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Header_Font(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Body_Font(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Footer_Font(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Navigation_Menu_Font(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Button_Font(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Header_Font_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Body_Font_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Footer_Font_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Navigation_Menu_Font_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Button_Font_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Header_Background_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Body_Background_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Card_Footer_Background_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Navigation_Menu_Background_Color(Selected_App_Custom_Design dto);
        Task<string> Update_End_User_Button_Background_Color(Selected_App_Custom_Design dto);
        Task<string> Delete_End_User_Selected_App_Custom_Design(Selected_App_Custom_Design dto);
        Task<bool> Validate_Client_With_Server_Authorization(Report_Failed_Authorization_History dto);
        Task<string> Insert_Report_Failed_Client_ID_History_Record(Report_Failed_Client_ID_History dto);
        Task Create_WebSocket_Permission_Record(WebSocket_Chat_Permission dto);
        Task<bool> Email_Exists_In_Pending_Email_Registration(string email_address);
        Task<bool> Email_Exists_In_Login_Email_Address(string email_address);
        Task<bool> ID_Exists_In_Users_ID(long id);
        Task<long> Read_User_ID_By_Twitch_Account_ID(long twitch_id);
        Task<long> Read_User_ID_By_Twitch_Account_Email(string twitch_email);
        Task<bool> Email_Exists_In_Twitch_Email_Address(string email_address);
        Task<bool> ID_Exists_In_Twitch_IDs(long twitch_id);
        Task<long> Read_User_ID_By_Discord_Account_ID(long discord_id);
        Task<long> Read_User_ID_By_Discord_Account_Email(string discord_email);
        Task<bool> Email_Exists_In_Discord_Email_Address(string email_address);
        Task<bool> ID_Exists_In_Discord_IDs(long discord_id);
        Task<User_Token_Data_DTO> Read_Require_Token_Data_By_ID(long end_user_id);

    }
}
